version: "2"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  web:
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    build: web/
    depends_on:
      - db
    volumes:
      - "./web/src:/web"
    links:
      - db
  dashboard:
    command: "python flask_system.py"
    environment:
      PYTHONUNBUFFERED: 1
    build: dashboard/
    ports:
      - "5000:5000"
    volumes:
      - "./dashboard:/dashboard"
volumes:
  dev_volume:
    driver: local
